### ISSUE TITLE
option to return only first result on ambiguous grammars

### ISSUE THREAD

**Issue by seiyria** [Hardmath123/nearley#100]
While I work to figure out why my grammar is ambiguous, it would be great to be able to tell nearley that I just want the first result that it gets (so far that's been working fine). Right now I'm getting ~25k results and while I'd like to fix my grammar, I'd also like to shortcut the process while I figure it out.

Somewhat related: is there an easy way to figure out where the ambiguities stem from?

**Comment by Hardmath123** [comment]
Can't you just do `the_result_i_care_about = results[0]`? Unfortunately, I can't just "throw out" ambiguities because they might get resolved later on in the parse.

Figuring out where ambiguity stems from is HARD (as in "factoring big numbers is hard" kind of hard). My recommendation is that you use `nearley-test` to print out the ambiguous results on small inputs to see how they differ. Use this information to isolate which nonterminals can be parsed ambiguously. Often this is quite unobvious—I guess it's the price you have to pay for an expressive parser that parses whatever you throw at it!

**Comment by seiyria** [comment]
So, I did manage to figure it out. I had two stray whitespace terminals that, depending on indentation, gave me between 48 and 25k results. Removing the bad entries solved a LOT of my problems. However, I still felt it was worth asking the question, just in case it was possible. I don't really understand the intricacies of parsers if you can't tell, haha. 

Thanks for the update! I'll close this since my questions were answered.
