### ISSUE TITLE
can you use nearley in a web worker?

### ISSUE THREAD

**Issue by seiyria** [Hardmath123/nearley#101]
I'm trying to make a realtime design tool that has a code editor, and a frame that updates live every few seconds (like plnkr, for example). The problem is, nearley chokes the browser for a few seconds while it parses the code in the editor. I think if I could offload nearleys parsing to a web worker this problem would be mitigated, but I'm not sure where to start getting it to work there.

**Comment by bjskistad** [comment]
(I would also like to see the demo. :))

**Comment by seiyria** [comment]
Thanks! I'm still building out the list of examples, but [here's a simpler example](http://deck.zone/#/embed/-KHIIvnDYrU_laodzCCd;scriptId=-KJQhPJrv4mpitmMJ63U;tabs=result,code) and [here's a more complex example](http://deck.zone/#/embed/-KJmosrkxknLr6-G2JT5;scriptId=0;tabs=result,code) (it'll probably take some time to load) for you @Hardmath123 and @bjskistad. I'm actually working on adding an examples section to the site right now.

There's a bit more to web workers than not touching the DOM as far as I can tell; you also need to have a self contained function (it cannot access any variables outside of its own scope). What a lot of libraries will do is let you pass in a function and it will generate a Blob and give that to a Worker instance.

[See this library code](https://github.com/haochi/angular2-web-worker/blob/master/web-worker.ts#L52-L61) (and the [readme](https://github.com/haochi/angular2-web-worker#api)).

The unfortunate part with this is that trying to run a small bit of code -- `[Parser.feed](https://github.com/Hardmath123/nearley/blob/master/lib/nearley.js#L201-L247)` -- is that there are a lot of variables that are outside the scope of that function, meaning the Worker doesn't do anything. 

That's my understanding (and I'd love to be proven wrong). FWIW, I did try implementing this a bit earlier and it didn't work out. :( I'd be happy to be proven wrong though!

Also, I figured that putting it in a Worker would make it so I don't need a server to constantly process (and possibly render) the data. They're just so restrictive, it's hard to actually do anything with them, it feels like.

**Comment by bobbybee** [comment]
It's worth noting actually parsing the text every time isn't necessary if all you want is syntax highlighting or something like that..

**Comment by seiyria** [comment]
I don't want just syntax highlighting. Those are static demos, but it is also possible to do real time editing (as I eluded to in my first post). In that case, it is necessary for nearley to run so I know what operations to execute.

**Comment by bobbybee** [comment]
@seiyria Oh, neat. Well, good luck then :-)

(You might be able to do something clever, like only reparsing lines which changed, or maybe even more aggressive.)

**Comment by seiyria** [comment]
@bobbybee thanks! As for only reparsing lines that changed... I think that'd be tricky, and I wouldn't really know where to start with that. I would love to do that because it sounds like it would be a lot better than reparsing the whole thing every time, but I don't think I know how to do that.

**Comment by bobbybee** [comment]
@seiyria @Hardmath123 will have to help you with the specifics of how to do this correctly, but to start off, you'll want to track efficiently changes per frame -- and no, diff'ing the strings is a bad idea :stuck_out_tongue:

**Comment by Hardmath123** [comment]
Kyle—

I got nearley to work in a WebWorker. Here is what I did:

First, we have a directory tree structure as shown:
```
├── csscolor.js
├── index.html
├── nearley.js
└── worker.js
```
`nearley.js` and `csscolor.js` are taken directly from the nearley repo; `csscolor.js` is one of the examples, compiled as usual.

In `worker.js`, we have
```
var window = self;

importScripts('nearley.js', 'csscolor.js');

onmessage = function(str) {
    var p = new nearley.Parser(csscolor.ParserRules, csscolor.ParserStart);
    p.feed(str.data);
    postMessage(p.results);
}
```
and in `index.html`, we have
```
<script>
window.onload = function() {
    var w = new Worker('worker.js');
    w.onmessage = function(m) {
        console.log("Got message!");
        console.log(m);
    }
    w.postMessage("rgb(0,0,0)");
}
</script>
```
Then, if you open the page in your browser, you should see the parse result appear in the console.

Some points to consider:
- The `var window = self;` is used to set the "global" object in the worker context, because `window` is not defined.
- I have only tested this in Safari, but it should work in other browsers (perhaps with minor modifications?).
- In practice, you would want to be more careful about error handling by catching a parse error and sending a different message. But this minimal example should be enough to get you started.

I have packaged my test in the following ZIP file, uploaded to Github: [nearley-in-a-worker.zip](https://github.com/Hardmath123/nearley/files/310465/nearley-in-a-worker.zip)

I hope that helps solve your problem; let me know if you need further help. Again, I'm super-excited by your project and would be thrilled to check it out when it's ready. :-)

P.S. The "incremental" approach others are suggesting is, to be honest, rather tricky. Personally, I wouldn't open that can of worms.

**Comment by seiyria** [comment]
Thanks @Hardmath123! I had never seen `importScripts` used before so I had no idea how it works. I might end up giving this a try tomorrow, since it looks like what you have is a solid start.

And of course, thanks for all the support. You have a great community and a great project, and I'm happy to have chosen it (not that I had any others in mind, of course!).

**Comment by Hardmath123** [comment]
Aww, Kyle, that made my day. :D

**Comment by seiyria** [comment]
Thanks again for the example. It took me a bit to be able to get around to it, but I finally did get it working (and the performance I was looking for is totally there). I had to figure out how to make it work with webpack, but after that, it was smooth sailing. Your example helped a lot, too!
