### ISSUE TITLE
Don't depend on a Git repository in package.json

### ISSUE THREAD

**Issue by moll** [Hardmath123/nearley#102]
Hey,

I'm checking out Nearley and noticed it depends on a Git repository (https://github.com/tabatkins/railroad-diagrams). Please don't. That's not particularly future proof, especially in the light of recent SNAFUs regarding retracted NPMs (e.g. left-pad). If that author hasn't published the version Nearley needs, please consider forking and/or publishing it as a scoped module under your own NPM username.

**Comment by Hardmath123** [comment]
Hello moll,

I appreciate your concern for future-proofing nearley's package.json. However, I do not think the railroad-diagram situation is worth worrying about. When developing for nodejs, we make certain assumptions about services like GitHub and npm staying alive, and I think it is worthwhile to accept those assumptions rather than be paranoid about future-proofing against them. That is an endless rabbit-hole I would rather not venture down into. I think an I'll-cross-that-bridge-when-it-comes attitude is more productive in the fast-moving nodejs ecosystem, and for me it has worked well for over two years of nearley-development.

The left-pad situation was regrettable, but I believe that the problem there was that so many people felt the need to include something so frivolous as a dependency (I am extremely picky about adding more dependencies to nearley). The railroad feature is small, non-essential, and currently used by exactly zero people that I know of. In the worst-case scenario, I can always ship off a copy of the dependencies' sources with nearley. But I do not want to publish a copy of an old version of someone else's work under my name just to appeal to a package manager, let alone a package manager as whacky as npm!

 P.S. In theory I'm working on a homegrown in-house version of a railroad diagram generator—a more worthwhile contribution might be to finish that off for me! ;-)

**Comment by moll** [comment]
Thanks for the response.

Necessity of having GitHub up while developing (or at least when starting) is perhaps tolerable, but not while deploying. People deploying through NPM proxies with locked versions (or shrinkwrapped dependencies) are entirely independent of the global NPM site. There's no comparable GitHub proxy for that and I don't think there's a need for it. I would argue repositories are not a good dependency source solution.

There's no need for slippery slopes. Not using dependencies outside of NPM is all I'm advocating. That, and not locking patch versions (for libraries), but the latter you're not doing.

As a quicker fix, you could move the railroad dep to an optional dependency, saving builds from breaking when GitHub et al. are unavailable. After that, maybe extract charting to an independent module. :)

**Comment by Hardmath123** [comment]
Ah, I'm not familiar enough with the `package.json` format to create an "optional dependency". If you could create a PR that lets me do something like

`npm install -g nearley --without-railroad-diagrams`

or something, I would be happy to merge it. :-)
