### ISSUE TITLE
Parsing never ends

### ISSUE THREAD

**Issue by matthew-dean** [Hardmath123/nearley#105]
What does it signify if the generated parser never terminates when parsing, yet no error is thrown? It would be helpful to have a list of common mistakes, perhaps.

**Comment by bobbybee** [comment]
It's possible you may just have such an ambiguous grammar and a large input file that it takes a looooong time. Not exactly nearley's fault, but some more debugging information might be useful here (at least nearley-test reporting this type of thing).

**Comment by Hardmath123** [comment]
Could you post your grammar and the input that causes it to fail? I see two possibilities: one, that you have a very inefficient grammar, and two, that there is a bug in nearley. I need more information to diagnose either issue.

**Comment by matthew-dean** [comment]
> one, that you have a very inefficient grammar

Since I am a grammar noob, that is a very strong possibility. A far as large input, I tried it with tiny input with the same result.

Gist: https://gist.github.com/matthew-dean/a08828743da5c4cb76aefc81168d8ce4
Fail input: ".box { a: b; }"

This was originally converted from nearley to PEG.js, and am trying again with nearley since the PEG.js generated parser was a bit slow. But could be because I have some crap ambiguous grammar in there.

**Comment by Hardmath123** [comment]
Off the top of my head, you're going to have ridiculous amounts of ambiguity because of how you handle whitespace. `_ Root:* _` and `Rule -> _ Comment _` mean that ws at the beginning of an input can be parsed in many, many ways. Same for ws between inputs. That's part of your problem.

Have you looked into using a tokenizer?

Also, this is a really cool grammar, I absolutely love it. Really cool to see LESS's grammar formalized; try using nearley-railroad to make a railroad diagram, which would look fantastic on the LESS site (like on http://json.org ). :-)

**Comment by Hardmath123** [comment]
Uh, Matthew, I just ran your grammar and fail case, and… it runs just fine on my (old and slow) Mac! Sure, you get lots of results, but it definitely finishes parsing.

![screen shot 2016-07-04 at 10 15 33 am](https://cloud.githubusercontent.com/assets/5202416/16567155/484d4828-41d0-11e6-8c86-5598bdafa71e.png)


If you're using `nearley-test`, perhaps you forgot to hit `^D` to actually send it the input? Happens to me, too. :-)

**Comment by Hardmath123** [comment]
(P.S. I took the liberty to make http://output.jsbin.com/jovukerino and I think it looks pretty rad.)

**Comment by matthew-dean** [comment]
@Hardmath123 Thanks for the praise! As I may have mentioned in the past, this is exploratory work to look at ways to make the Less.js parser more manageable and possibly faster. But there's value in having a formal grammar available on the Less site as well. I'm not the first to do it though. See: https://github.com/antlr/grammars-v4/tree/master/less

It's a bit out of date but exists.

**Comment by matthew-dean** [comment]
Also: awesome on the tree diagram! I would for sure propose using that, although I may want to more precisely name a few things.

Not sure why I couldn't get any output. I tried using the API and nothing happened. I did:
```
    var nearley = require("nearley");
    var grammar = require("../lib/less/parser/less_nearley_parser");
    var p = new nearley.Parser(grammar.ParserRules, grammar.ParserStart);
    p.feed(".box { a: b }");
```
It stops at `p.feed()`.

As for the whitespace, chalk that up to me not knowing exactly what I'm doing. It's hard to reason about where the optional whitespace should go, either within one of the definitions or outside one of the definitions that references it.

Ohhh.... I guess you're saying if there's multiple definitions that start with whitespace, then I'm incurring a match penalty because all match for the first character. That makes sense.

**Comment by Hardmath123** [comment]
> Not sure why I couldn't get any output. I tried using the API and nothing happened. I did:
> ```
>     var nearley = require("nearley");
>     var grammar = require("../lib/less/parser/less_nearley_parser");
>     var p = new nearley.Parser(grammar.ParserRules, grammar.ParserStart);
>     p.feed(".box { a: b }");
> ```
> It stops at `p.feed()`.

Well, I just tried it, and it works just fine for me. I copy-pasted your gist to a file, `nearleyc`'d it to `less.js`, and then ran the 4 lines above (replacing with the correct path to `less.js` on the second line). It runs instantly, and `p.results` is populated when it's done.

Maybe you need to update nearley and nearleyc (with -g)? Does it work using `nearley-test`?

> Ohhh.... I guess you're saying if there's multiple definitions that start with whitespace, then I'm incurring a match penalty because all match for the first character. That makes sense.

Not quite. Nearley's algorithm actually prevents this matching penalty from being as taxing as it would be for PEGjs!

I'm saying that when you have

```
a -> _ b
b -> _ "c"
```

then the string `     c` with a lot of leading whitespace can be parsed in a lot of ways. Why? Because you can divide up the leading whitespace between the `_` in `a` and the `_` in `b`. For example, three parsings are

```
((  b))
and
( ( b))
and
(  (b))
```

Pick a convention; I would put whitespace in the outer nonterminal that references the inner one. The other way would probably work fine too. But if you do *both*, then that's bad. :-)

**Comment by matthew-dean** [comment]
Ah ok I get it.

I'll try the parsing again. No clue.
