### ISSUE TITLE
Very slow performance for JSON grammar.

### ISSUE THREAD

**Issue by bd82** [Hardmath123/nearley#111]
Hello.

### Background
I'm trying to add nearley to a benchmark of multiple javascript parsing libraries.
For this purpose I've implemented a JSON grammar using nearley
and have "fed" it my standard sample (±1,000 lines) json input.

### Issue
On my modern MacBook Pro (4ghz I7) parsing this sample takes ±6-7 seconds.
This is as much as **three order of magnitudes** slower than other Parsing libraries I've used.

[**Reproducing html page**](http://sap.github.io/chevrotain/performance/index_nearley.html
)
* This page prints the total parsing time to the **console**.
* It may take a few seconds until the page is responsive to allow opening the development tools.

### Sources:
* [Grammar](https://github.com/SAP/chevrotain/blob/47f40b1f464bae834dad1af5cbe3654671b5f73b/performance/jsonParsers/nearley/json_grammar.ne)
* [Generated Code](https://github.com/SAP/chevrotain/blob/47f40b1f464bae834dad1af5cbe3654671b5f73b/performance/jsonParsers/nearley/nearley_json_parser.js)
* [benchmark code](https://github.com/SAP/chevrotain/blob/47f40b1f464bae834dad1af5cbe3654671b5f73b/performance/index_nearley.html#L22)
* [1,000 lines sample input](https://github.com/SAP/chevrotain/blob/47f40b1f464bae834dad1af5cbe3654671b5f73b/performance/samples/1K_json_no_escaping.js)

### Extra Details
I'm even ignoring whitespace (pre-processing it out of the input) and literal string escaping handling to simplify the grammar. so its a strict subset of the JSON grammar which makes it **extremely** simple as the base JSON grammar is already quite simple...

### Questions
* Am I doing something incorrectly / missing something?
* Should this be examined using a separate tokenizer as well?

Thanks.

**Comment by bobbybee** [comment]
What does nearley-test output? (Is it ambiguous?)

**Comment by Hardmath123** [comment]
You should use a tokenizer, of course.

You have to realize that nearley is a table-based parser, which means it creates a fresh row in a large table for each token that comes in. This is the core of the Earley algorithm, which makes it so much more powerful than boring old naïve parsers.

Now, if your tokens are characters, this obviously chokes up the table. Your 24KB test input creates 24K rows in the table. If you tokenize ahead-of-time, though, then there will be far fewer rows in the table, and all the "stupid" parsing (i.e. literals) is done with your lexer's regexes which don't need nearley's super-fancy features to get the job done. Win!

P.S. JSON is a meh benchmark because recursive-descent parsers have an obvious advantage here. You could write a ridiculously fast recursive-descent JSON parser in like 10 lines of Haskell. Nearley would shine in a benchmark where things are a little less obvious. :-)

**Comment by Hardmath123** [comment]
(Update: I had a free evening, so I implemented Joop Leo's right-recursion optimization. Grab the latest nearley version to try it out. If I did it right, this should make your JSON example much faster, even without tokenization.)

**Comment by bd82** [comment]
> You should use a tokenizer, of course.

I will play around with using a Tokenizer and see how this effects the performance.

> Now, if your tokens are characters, this obviously chokes up the table. Your 24KB test input creates 24K rows in the table. If you tokenize ahead-of-time, though, then there will be far fewer rows in the table

Does not this mean that once the input size increases we will be back to square one in regards 
to table size? lets say I do use a tokenizer. but instead of 1,000 lines sample use 10,000 lines.
Won't I encounter the same problem? (instead of X chars, X Tokens).


> P.S. JSON is a meh benchmark because recursive-descent parsers have an obvious advantage here. You could write a ridiculously fast recursive-descent JSON parser in like 10 lines of Haskell. Nearley would shine in a benchmark where things are a little less obvious. :-)


I Just JSON as the sample grammar because:
* It is a very simple grammar, so it is easy to understand each implementation.
* Many Parsing Generators / Libraries provide a JSON example.

Could you provide an example of a **small** grammar where things are a "little less obvious"?

**Comment by bd82** [comment]
> (Update: I had a free evening, so I implemented Joop Leo's right-recursion optimization. Grab the latest nearley version to try it out. If I did it right, this should make your JSON example much faster, even without tokenization.)

It does help somewhat, runtime is now 5-5.5 seconds instead of 6.5-7 seconds.
I'm still looking for an order of magnitude improvement at the very least. 
hopefully tokenizing will provide a greater benefit.

**Comment by bd82** [comment]
> What does nearley-test output? (Is it ambiguous?)

How can I run nearley-test programmatically ?  it is not very practical to input large samples
from the command line...

anyhow running:
```
nearley-test nearley_json_parser.js -i '{"key1":[1,2,3],"key2":"value2"}'
```

**output**:
Table length: 1
Number of parses: 0
Parse Charts
Chart: 0
0: {json →  ● json$subexpression$1}, from: 0
1: {json$subexpression$1 →  ● object}, from: 0
2: {json$subexpression$1 →  ● array}, from: 0
3: {object →  ● "{" object$ebnf$1 "}"}, from: 0
4: {array →  ● "[" array$ebnf$1 "]"}, from: 0

Parse results: 
[]

I simplified the grammar (no white space handling) to hopefully avoid ambiguities...

**Comment by bd82** [comment]
### Results
With a Tokenizer this is **±50 times faster. **
at around ±120ms.

[Reproducing HTML Page with a Tokenizer](http://sap.github.io/chevrotain/performance/index_nearley_tokenizer.html)

The overall **relative** performance is still **quite low**.
[JSON Parsers performance comparison](http://sap.github.io/chevrotain/performance/)

### Suggestion:
Considering JSON is one of the most trivial of grammars, perhaps it is **important**
for Nearley to have its own built-in tokenizer?
Particularly after seeing how glueing together an external tokenizer resulted in
incorrect error messages (the error reported the index of the offending token, not it's offset.



### Questions:
* Is there something else I can do to improve the performance?
* Any way to improve the [grammar](https://github.com/SAP/chevrotain/blob/e16cac557f2a66a9ea92675f7845a976674c2a9c/performance/jsonParsers/nearley/json_grammar_tokenizer.ne)? is it ambiguous for some reason?

**Comment by Hardmath123** [comment]
Okay, firstly, you're making it sound like things are out-of-control-slow here, but your benchmark suggests that nearley is almost *twice* as fast as Jison, Chevrotain, and Ohm *combined*. Unless I'm running your benchmark wrong (though I don't see how I could mess up clicking the link in your post), I see no cause for concern.

![screen shot 2016-07-25 at 9 03 50 am](https://cloud.githubusercontent.com/assets/5202416/17108060/c39a8ae6-5246-11e6-8b5f-9674a4100369.png)

I find it hard to believe that the Leo optimization I pushed last night didn't make a more dramatic difference. On my sluggish home machine, running benchmarks in node (with a hard cap on memory usage), it brought performance from "segfault" to like 3 seconds to parse your 1k JSON thing without tokenizing. Maybe you had the old nearley cached.

If you want to improve the performance of your grammar even more, try compiling with special postprocessors that always return null, i.e. `{% function(d) {return null;} %}`. But FWIW, your grammar doesn't look ambiguous.

In any case, JSON is, what, LL(1)? Try, maybe, a simple arithmetic language with optional delimiters. Suddenly you get PegJS freezing your browser because of some mutual left-recursion, and Jison is throwing shift-reduce conflicts and setting precedence is hard and you need exponentiation to group the other way and everything is on fire. On the other hand, nearley sails through the left-recursion and tells you the ambiguity that leads to the shift-reduce conflict and precedence is easy and idiomatic. In four lines of code.

```
sum     -> sum "+" product | sum "-" product | product
product -> product "*" exp | product "/" exp | exp
exp     -> base "^" exp | base
base    -> "1" | "(" sum ")"
```

By the way, it's strange that nearley-test with `-i` is acting whacky. I always run nearley-test by piping to it:

```sh
$ echo -n '{"key1":[1,2,3],"key2":"value2"}' | nearley-test ~/lab/jsonp.js
Table length: 33
Number of parses: 1
```
I'll look into what's up.

But look, nearley is a *parser*, not a *tokenizer*. Its job is to parse whatever stream of junk you feed it. The stream of junk doesn't even need to resemble a lexical token: you could hook nearley up to a websocket connection and "parse" the stream of incoming messages if you feel like it.

As it stands, writing a lexer is trivial. Anyone can do it in a couple of hours and there are literally dozens you could use off-the-shelf. Writing an Earley parser, on the other hand, is *hard*. nearley has been around for, what, 3 years now? We *still* get stuff wrong every once in a while.

So I argue that, for example, the token index is the *right* thing for nearley to report in its error message, because that error message is to debug the *parser*, not the input to the parser. A lexer would preserve lexical information (`{file: something.json, line: 10, column: 4}`) which the parser's client would use to print an error message for the user. That's the right thing to do.

Sure, maybe someday someone will PR a decent tokenizer that I'll merge for convenience. But it had better be a *really* good tokenizer that is integrated *really* well with the rest of the nearley ecosystem; otherwise it offers no benefit to users other than saving them an extra "npm install" step.


Two other things:
- When you say "±50ms", that doesn't make any sense. I spent a long time wondering if you made a typo, but then you did the same thing many times so I am guessing you meant "50ms, approximately". The ± notation should be used as "50±2ms", which says that the mean was 50ms and the standard deviation was 2ms. For approximate values, people generally use "~50ms".
- It's funny how you **bold** arbitrary words in your sentences and divide your posts **into** sections; it **makes** it feel like reading a Wikipedia **entry**. :D

**Comment by bd82** [comment]
I'll reply in multiple comments to keep each comment on a specific item.

> Okay, firstly, you're making it sound like things are out-of-control-slow here, but your benchmark suggests that nearley is almost twice as fast as Jison, Chevrotain, and Ohm combined. Unless I'm running your benchmark wrong (though I don't see how I could mess up clicking the link in your post), I see no cause for concern.

From the benchmark results I am guessing you are running the benchmark on **Safari** ?
Safari has a [performance bug](https://bugs.webkit.org/show_bug.cgi?id=152578) with certain patterns in regular expressions combined with large inputs.

The Jison and Chevrotain Parsers both use a regular expression that is affected by that bug.
```javascript
 /"(?:[^\\"]+|\\(?:[bfnrtv"\\/]|u[0-9a-fA-F]{4}))*"/ // for a stringLiteral
```

Here are the results running on my MBP and chrome 51:
![Perf on chrome](http://sap.github.io/chevrotain/photos/perf_chrome.PNG)

Which is why I was sounding so gloomy :cry: 
Keep in mind that this is the same Javascript engine (V8) which is used in node.js.

I'm interested in learning the Earley algorithm, perhaps after doing so I'll manage to find 
some time to profile nearley and understand what is using all the cpu cycles.

**Comment by bd82** [comment]
**On Parsing vs Lexing.** 

I completely agree that writing a Lexer is trivial.
And that a Parsing Library does not have to include a separate tokenizer.
My own Parsing library was initially a pure parser without any lexer capabilities (not even char stream parsing).

**The question is how often do Nearley users have to use a separate tokenizer?**
Was my issue unique? would a separate tokenizer be required in your simple arithmetic example
for large enough inputs? If this is often the case then perhaps it is something more important.
On the other hand if the performance of a char stream nearley parser can be improved so a tokenizer
would only be required in special edge cases for unique optimizations and control then it is irrelevant.
(80/20 rule)

These are obviously "product management" level decisions, and it is your project so I'm in no way trying to tell you what to do and there is not even a "right" decision.

This is just the perspective of someone who briefly used Nearley and had to deal with an extra level of complexity that I'd rather have avoided.

**Comment by bd82** [comment]
>I find it hard to believe that the Leo optimization I pushed last night didn't make a more dramatic difference. On my sluggish home machine, running benchmarks in node (with a hard cap on memory usage), it brought performance from "segfault" to like 3 seconds to parse your 1k JSON thing without tokenizing. Maybe you had the old nearley cached.

I tested again and verified the right nearly.js is loaded in the developer tools.
* Chrome
   - 2.6.0  ~9.5 seconds.
   - 2.7.0  ~6.5 second.

* FireFox
  - with 2.6.0 I get ever increasing runtime duration 16 -> 34 -> 43 -> 63 seconds (memory leak?)
  - with 2.7.0 ~7 seconds **stable**.

That is indeed a much bigger difference than I noticed before.

**Comment by bd82** [comment]
>  When you say "±50ms", that doesn't make any sense. I spent a long time wondering if you made a typo, but then you did the same thing many times so I am guessing you meant "50ms, approximately". The ± notation should be used as "50±2ms", which says that the mean was 50ms and the standard deviation was 2ms. For approximate values, people generally use "~50ms".

Thanks for the correction.

> It's funny how you bold arbitrary words in your sentences and divide your posts into sections; it makes it feel like reading a Wikipedia entry. :D

English is not my native tongue and it seems to help me organize my writing and explain myself.
I hope it is funny in a positive manner.  :smile:

**Comment by bd82** [comment]
>In any case, JSON is, what, LL(1)? Try, maybe, a simple arithmetic language with optional delimiters. Suddenly you get PegJS freezing your browser because of some mutual left-recursion, and Jison is throwing shift-reduce conflicts and setting precedence is hard and you need exponentiation to group the other way and everything is on fire. On the other hand, nearley sails through the left-recursion and tells you the ambiguity that leads to the shift-reduce conflict and precedence is easy and idiomatic. In four lines of code.

These capabilities are awesome from the perspective of easy of use and possible languages Nearley can parse, but the discussion here is about **performance**. Maybe even performance in a very specific use case although I'm worried this may be a general problem. Not which is the "best" Parser Library (if such a thing even exists).

lets try to limit the discussion to that, because this is already becoming a big thread.

**Comment by Hardmath123** [comment]
Urrghh the Safari thing is annoying. But I'm glad to see that the Leo optimization produces a visible performance boost, at least in one browser. My hours of debugging yesterday were not wasted!

> These capabilities are awesome from the perspective of easy of use and possible languages Nearley can parse, but the discussion here is about performance. Maybe even performance in a very specific use case although I'm worried this may be a general problem.

What I mean is that performance depends a lot on the kind of language you're parsing. An LL(1) language parser can be hyper-optimized to its domain, but it won't parse infix operators. If you want the flexibility, there's a cost associated.

I'm pretty sure nearley's slowness isn't specific to this particular grammar. Historically, all the nearley optimizations have been algorithmic, speeding things up by an _asymptotic factor_. So nearley parses [practically](https://jeffreykegler.github.io/Marpa-web-site/#quibbles) all BNF grammars in linear time. And until now, this has always been "good enough" for everyone using it, even without tokenizers. The time saved in writing grammars has always been way more than the collective gains from using a faster but yuckier parser generator.

Obviously, I'm sure someone smarter than me can optimize the actual JS to the hilt, which would speed things up by a potentially massive _constant factor_. Indeed, I'd be grateful if someone did; though, judging from the past 3 years of PRs, that's unlikely to happen. Regardless, I personally don't know the internals of JS well enough to do that, and I'd rather spend my time on adding cool new features like the railroad diagrams generator (I think nearley's the only parser generator that does this). That's why nearley is an asymptotically-fast but practically-slow parser.

> English is not my native tongue and it seems to help me organize my writing and explain myself.
I hope it is funny in a positive manner.

Absolutely, yeah, it's so much better than people who type bug reports as a massive paragraph, or (even worse) a single sentence.

**Comment by bd82** [comment]
Please review:  https://github.com/Hardmath123/nearley/pull/112
On chrome it improved the performance by x2-x3 depending on the specific benchmark and usage of a tokenizer.


This is not about smarts, I just have experience in micro optimizing Javascript logic...
I think if **findLeo** can be refactored to avoid recursion there is another potential for a speed boost
as last I heard javascript engines do not perform tail call optimization.

> The time saved in writing grammars has always been way more than the collective gains from using a faster but yuckier parser generator.

This depends on the use case for example: interactive (parser in an IDE) or not (parser in a compiler) the expected input size and how many times it is actually used. In cases where performance is 
of the highest concern sometimes even fast parser generators are not enough and hand crafted parsers are used instead.

>cool new features like the railroad diagrams generator (I think nearley's the only parser generator that does this).

I've actually implemented the same thing (using the same railroad library) in Chevrotain.
* [Example CSS Diagrams](https://rawgit.com/SAP/chevrotain/master/examples/grammars/css/css_diagrams.html)
* I've added logic to perform some highlights and navigation to none-terminals (on click).
   If you are interested you can see the related code [here](https://github.com/SAP/chevrotain/tree/master/diagrams): 

>What I mean is that performance depends a lot on the kind of language you're parsing. An LL(1) language parser can be hyper-optimized to its domain, but it won't parse infix operators. If you want the flexibility, there's a cost associated.

There are some ugly patterns to allow parsing infix operators (and precedence) in LL(1) parsers.
I do however agree that left recursion is the most natural and clear way to express infix operators grammar. I've also read a little about Earley algorithm and found some references that it 
is indeed slower on average in **practice**. And after looking at all the work being done in building the parsing table on every token I can understand why there is a large constant factor.

**Comment by Hardmath123** [comment]
Thanks! I reviewed #112 and merged it as well; you can see my comment on that PR.

> This is not about smarts, I just have experience in micro optimizing Javascript logic...

Hmm, yeah, that's something I have yet to learn. My hope is that as nearley matures, people with JS-specific optimization knowledge can profile the parser and clear the bottlenecks, while people with algorithmic knowledge can help build the neat tooling that makes nearley unique. I think tooling is the most important facet when it comes to this kind of software: I borrow this philosophy from Elm, which is a mediocre language made ridiculously powerful with its brilliant tooling.

> This depends on the use case for example: interactive (parser in an IDE) or not (parser in a compiler) the expected input size and how many times it is actually used. In cases where performance is of the highest concern sometimes even fast parser generators are not enough and hand crafted parsers are used instead.

Yeah, I agree, I guess no nearley user has ever had to parse a thousand-line file in real-time before. There's a first time for everything!

> I've actually implemented the same thing (using the same railroad library) in Chevrotain.

Cute. Recently, I've been toying with using [this LaTeX package](http://texdoc.net/texmf-dist/doc/latex/mdwtools/syntax.pdf) as an alternative for syntax diagrams. You might be interested.

Though, if the representation of the BNF is in a nice data structure, I wonder what it would take to have free translation between nearley/Chevrotain/PegJS grammars. Does there exist a universal standard file format for BNF?

**Comment by bd82** [comment]
I've updated the benchmark to use version 2.7.1 which includes the optimization.

> Does there exist a universal standard file format for BNF?

First time I thought to look for one, but apparently there is and its ISO certified :smile: 
http://www.cl.cam.ac.uk/~mgk25/iso-14977.pdf

>I wonder what it would take to have free translation between nearley/Chevrotain/PegJS grammars.

I once had to translate a grammar in an EBNF like notation to an Antlr grammar notation. 
Naturally I was too lazy to do so manually so I built a separate parser using Scala Parser Combinators
to perform the translation. :) 

Those translation are not hard  when you are dealing with just the grammar. however a productive grammar file may have additional headers / code snippets so getting such a thing to do 90% of the job should be easy, but 100% (production quality) may be harder.

Btw with Chevrotain translation will be harder as Chevrotain does not have a separate EBNF like notation from which the parser is generated/created. Instead you write pure javascript code using an internal Javascript DSL.

Example:
```javascript
$.value = $.RULE("value", () => {
            $.OR([
                { ALT: () => { $.CONSUME(StringLiteral) }},
                { ALT: () => { $.CONSUME(NumberLiteral) }},
                { ALT: () => { $.SUBRULE($.object) }},
                { ALT: () => { $.SUBRULE($.array) }},
                { ALT: () => { $.CONSUME(True) }},
                { ALT: () => { $.CONSUME(False) }},
                { ALT: () => { $.CONSUME(Null) }}
            ], "a json value");
});
```

So this means the generation must create a valid javascript program text which is probably harder.

With Parser Generators (Peg.js/Antlr/Jison/Nearley) you define a grammar in BNF style notation
and code is generated which implements your parser.

With Chevrotain the "flow" is in the **opposite** direction:
you write something that looks like an hand crafted Recursive Decent Parser.
and Chevrotain **"self parses"** (using Function.prototype.toString) the grammar's **implementation** to figure out the entire grammar structure / compute lookahead functions / draw diagrams / ....

This is very similar to **macros** in scheme. reflection on the structure of the code.
Only much uglier because it works on the **text** of the implemented grammar not its AST.

> I've been toying with using this LaTeX package as an alternative for syntax diagrams. You might be interested.

I'm not familiar with LateX, can I use such a thing easily in the browser ? Embed it in a markdown file?
I'm mostly interested in self documentation which is easily accessible on the web (HTML pages / EBNF notation in markdown files)

**Comment by bd82** [comment]
BTW the original issue (performance) is closed as far as I'm concerned.
The combination of a tokenizer and the optimization brought it up to more reasonable standards.

**Comment by Hardmath123** [comment]
LaTeX can be compiled down to PDF, and I think SVG as well. But both of those can be easily turned into high-resolution PNGs.

I'm closing this issue for now. If you find another place to optimize, do let me know.

Thanks again for your input—I appreciate it greatly.

**Comment by bd82** [comment]
@Hardmath123 No problem. and the feedback went both ways on this issue. :smile:

**Comment by mutech** [comment]
Reading this thread was a real pleasure. There were quite a few opportunities where egos could have been scratched, instead there was a very productive and polite exchange of know-how and ideas. This could serve well as an example in github-netiquette; said a voice from the back benches applauding ;-)
