### ISSUE TITLE
Rejection reason

### ISSUE THREAD

**Issue by solmsted** [Hardmath123/nearley#114]
It would be convenient if a postprocessor function could do something like:

``` JavaScript
function (data, location, reject) {
    return reject('custom rejection reason message');
}
```

Then the parse error that gets thrown could have a more useful message with helpful information to debug why something failed to parse.

**Comment by Hardmath123** [comment]
I'm not sure I understand. Could you explain how the "rejection reason" would be accessible from the parse?

"Rejection" is not a way to signal a parse error: rather, it's a way to allow a rule to prevent itself from being matched in specific cases where there is ambiguity (e.g. you don't want "if" to match as a variable name because it's actually a keyword).

**Comment by bobbybee** [comment]
@Hardmath123 What's the 'correct' way to generate human-readable parsing errors with nearley?

**Comment by Hardmath123** [comment]
"Parse failed at $last_token_lexical_location"

Or, if you're adventurous, "Parse failed at $last_token_lexical_location. Expected $expected_tokens" where you scrape $expected_tokens from the Earley table.

**Comment by solmsted** [comment]
I'm really looking for better ways to provide useful error messages when a parse failed.  Let's use your example of `if` as a reserved word.  Suppose I had some source text like:
```
int if = 3;
````
At some point a postprocessor function checks the variable name against a list of reserved words and rejects it.  When there are no alternate valid parses, nearley's `feed` method throws an error.  The error object contains an offset property where the token was that failed to parse but no information as to why it failed to parse.  Instead of saying "Parse failed at offset 4.",  I'd rather say something like "Parse failed at offset 4 because the reserved word `if` is not allowed to be used as an integer name.".

Reject feels like a convenient place to pass that information back out from the postprocessor function.  If there was another valid parse, obviously no error would be thrown and any rejection message should be discarded.  I'm sure there are other edge cases or internal implementation issues that I'm unaware of, so reject may not be the best API for this.  I'm not set on that API, just looking for anything to help with better error messages.

**Comment by Hardmath123** [comment]
Right, I understand what you're trying to do. It's an interesting problem. But `reject` is not the solution. For example, what if multiple rules called `reject` when a parse failed? `reject` isn't about throwing an error, it's about signaling a very specific condition to the parser.

I think it comes down to the fact that "if is not allowed to be used as an integer name" is a bit too specific as far as parser-capable error messages go—it's not something a parser should know. The way this should go down, ideally, is that the tokenizer classifies "if" as a keyword, not as a variable name, and so the parse fails at that point because it literally cannot find a variable name token. In this case, your best shot at an error message is "Expected variable name but got keyword", which I can totally live with.

Maybe you need to give a more motivating example of a "useful error message".

**Comment by tjvr** [comment]
@Hardmath123 Since we're not sure what to do about predicates, maybe we should consider this... if we're going to allow arbitrary code to modify the parse, I don't see why we can't allow it to raise errors! :P

**Comment by bobbybee** [comment]
> @Hardmath123 Since we're not sure what to do about predicates, maybe we should consider this... if we're going to allow arbitrary code to modify the parse, I don't see why we can't allow it to raise errors! :P

...I'm not sure I like where this is going :S

**Comment by Hardmath123** [comment]
True, Tim. But we want to be careful — there could be many `reject` messages thrown in a failed parse, so you need to know which one is the, for lack of a better term, is the "right wrong".

Error handling is fun!

**Comment by tjvr** [comment]
> there could be many reject messages thrown in a failed parse

True! I can't even think of a way to make sense of _that_. :P

**Comment by tjvr** [comment]
Closing, since this is scary & it's not obvious to anyone what it should do!
