### ISSUE TITLE
Way to serialise back to text ?

### ISSUE THREAD

**Issue by Xample** [Hardmath123/nearley#121]
Hi, I am just wondering if there is any way to serialize the parsed data back to text.

**Comment by bobbybee** [comment]
My gut feeling is that this is one of those hard problems like ambiguity detection (NP-complete maybe?), but @Hardmath123 can probably elaborate.

**Comment by Hardmath123** [comment]
No, NP-completeness has nothing to do with this.

1. If you used postprocessors, all hope is lost.
2. If you didn't use any postprocessors, just flatten the list-of-list structure nearley returns by default.

That being said, why would you ever want to do that kind of thing? If you use a parser, you already *have* the text.

**Comment by Xample** [comment]
@Hardmath123 this is for 2 ways editing. For example: an HTML parser generates a DOM. If you change an attribute within the HTML the DOM should reflect the change as well. Conversely, if I change the DOM, I wish the HTML to be updated accordingly. This is what a dom.asHTML() function should do. BTW, writing a serializer should be more simple than a parser.

**Comment by Hardmath123** [comment]
Yes, but it's not easy for nearley to serialize back automatically, because postprocessors mangle the data. For the use-case you described, you should almost certainly write your own custom serializer. As you said, it's simpler than a parser, and it gives you a lot more flexibility than a built-in serializer ever could.
