### ISSUE TITLE
Postprocessor called multiple times

### ISSUE THREAD

**Issue by stefda** [Hardmath123/nearley#144]
I'm trying to understand why the postprocessor in my simple grammar below gets called multiple times:

```
@builtin "whitespace.ne"
@builtin "number.ne"

date -> day_of_month _ month (_ year):? {%
  function (data) {
    console.log(data);
    return data;
  }
%}

day_of_month -> int
month -> "jan" | "feb" | "mar"
year -> int
```

Feeding a string "12 jan 2016" into the parser logs the following lines:
```
[ [ 12 ], null, [ 'jan' ], null ]
[ [ 12 ], null, [ 'jan' ], [ null, [ 2 ] ] ]
[ [ 12 ], null, [ 'jan' ], [ null, [ 20 ] ] ]
[ [ 12 ], null, [ 'jan' ], [ null, [ 201 ] ] ]
[ [ 12 ], null, [ 'jan' ], [ null, [ 2016 ] ] ]
```
But the actual `results` array on the parser output is:
```
[ [ [ 12 ], null, [ 'jan' ], [ null, [ 2016 ] ] ]
```

Why does the posprocessor get called multiple times and is there a way to tell when it's being called on data that corresponds to the final result?

**Comment by Hardmath123** [comment]
It gets called multiple times because each of "12 jan", "12 jan 2", "12 jan 20", "12 jan 201", and "12 jan 2016" is a valid `date` according to your grammar (you don't specify that a year is 4 digits).

Postprocessors should never depend on knowing whether it's the final result or not — in fact, they should never have side-effects period.

(Note to self: #33 is relevant but won't happen because we depend on postprocessor output to determine the parse if `reject` is used.).

**Comment by stefda** [comment]
Yeah that makes sense. Thanks for the quick answer!
