### ISSUE TITLE
Possible to round trip back to the source

### ISSUE THREAD

**Issue by zakhenry** [Hardmath123/nearley#155]
Is it possible (with `nearly`) to parse some source using a grammar into the AST, then with that AST "un-parse" it back to valid source.

Thinking along the lines of having a system that can take user input source and save it as the AST then present it back to them later for editing

**Comment by Hardmath123** [comment]
Why don't you just save the input source along with the AST?

nearley doesn't have a way to convert an AST to source text because the process of creating the AST loses information (for example, in most programming languages whitespace gets ignored, so how would nearley know the original whitespace of the source text?). However, it is easy to write a small recursive-descent program that turns an AST into *a* string that it might have come from (if you aren't using postprocessors, you can simply flatten the structure returned by nearley.)

**Comment by zakhenry** [comment]
Thanks, that covers my question. I thought it was the case, as yea things like whitespace are guaranteed to be lost, I guess it makes sense to keep their original input for debugging etc.

**Comment by bd82** [comment]
Saving the original input would not be enough in the general use case of building an editor.
because implementing features such as Formatting, Refactoring, Code snippets and such
would require the **concrete** syntax tree (not AST).

Is there something preventing you from assembling a concrete syntax tree data structure
instead of an AST which would contain all the syntactic information?
