### ISSUE TITLE
What does {% id %} do?

### ISSUE THREAD

**Issue by pepa65** [Hardmath123/nearley#244]
I have read the `README.md` here, and the [Nearley web page](http://nearley.js.org/). Then I was reading `how-to-grammar-good.md` and I've read the page about [Earley](http://hardmath123.github.io/earley.html). I understand what regular expression, Backus Naur Form, context free grammar, terminal, nonterminal, and ambiguous grammar mean, but when it said

> You should know nearley syntax well enough to understand what something like
> ```
> int -> [0-9]        {% id %}
>     | int [0-9]     {% function(d) {return d[0] + d[1]} %}
> ```
> means

I thought: no, not fully. Where can I learn more?

I understand the declaration syntax, and I know that JavaScript snippets can be included between `{%` and `%}`, but what does the `{% id %}` do? (I'm guessing the first argument of the function is the array of elements of the word, so the first 2 elements are returned.)

**Comment by deltaidea** [comment]
Yep, you got it right! See, it _is_ pretty straight-forward. 😄 

In the generated JS you can find this: `function id(x) {return x[0]; }` - this operation is so often-used that they include a helper for it. Since `{% ... %}` can contain any JS, `{% id %}` simply refers to this `id` function defined in the same file.

I agree, docs are lacking sometimes. At least the syntax is intuitive.

**Comment by tjvr** [comment]
Thanks for the question, and thanks @deltaidea for explaining!

We'd welcome PRs to improve the documentation. :-)

**Comment by pepa65** [comment]
So `id` means `return x[0]`which means output the first part of the match. This should be added into the README.md? I feel I don't have enough understanding to start issuing pull requests on the documentation yet... Here is to hoping for someone in the community who has mastered a bit more of this that can add a page? Or a few lines perhaps?!

**Comment by Hardmath123** [comment]
Also, @pepa65, we _do_ mention it in the README! https://github.com/Hardmath123/nearley#postprocessors

> data is an array whose elements match the nonterminals in order. **The postprocessor id returns the first token in the match (literally function(data) {return data[0];}).**

I guess the problem is that it's hidden away and hard to find — and I guess the solution is to restructure the documentation to be easier to skim. Currently, we have some sort of hybrid between an in-depth tutorial and legit documentation; maybe that needs to change…

**Comment by pepa65** [comment]
@Hardmath123 You are right, I must not have guessed it, but read it there..! The comment about `id` I didn't understand then. Maybe just including `{% id %}` there in the text would have clarified that.

Even though Nearley seems to be widely used, not a lot can be easily found about it on the internet .

**Comment by Hardmath123** [comment]
Well, nearley isn't _that_ widely used yet, and so there isn't really a corpus of blog posts/SO questions that normally comes up when you look up other established open-source projects. This issue tracker is the primary forum for discussing nearley…

You're welcome to help change that, though! A nice blog post about using nearley would help other new users, and also us developers (it helps us figure out what common issues are for first-time users). :-)
