### ISSUE TITLE
Nearley is very slow

### ISSUE THREAD

**Issue by notsonotso** [Hardmath123/nearley#250]
I migrated a few (simple) grammars from Antlr4, but are seeing some pretty serious performance problems. 

A "1;2-3;4" formatted line input of a few megs takes subsecond on Antlr4 but almost a minute in Nearly)

Any hints on how to improve performance?

**Comment by tjvr** [comment]
You've probably got something that's accidentally ambiguous. Can you share your grammar here? :-)

**Comment by Hardmath123** [comment]
In the spirit of https://accidentallyquadratic.tumblr.com and http://beza1e1.tuxen.de/articles/accidentally_turing_complete.html, maybe we should start an "accidentally ambiguous" gallery.

**Comment by deltaidea** [comment]
Idea: optional `strict` mode that exits early and give you an error on the first ambiguity. Bonus points for telling the exact rule stack and what are the ambiguous parsing paths. Extra bonus points for compile-time checks for trivial cases if the `strict` option is set to `true`.

**Comment by Hardmath123** [comment]
We've thought about this.

Detecting ambiguity at parse-time violates the spirit of Earley, which is that you maintain all possible parses as tokens come in. You can't really get around this because you never know when the token stream ends. Yes, you can have a .finish() or something that tells nearley when the token stream has ended, but at that point you've already finished parsing so why don't you just inspect `.results` yourself?

Detecting ambiguity at compile-time is an undecidable problem, in the sense that if you have an algorithm that can detect ambiguity in CFGs, then you can refactor it to also solve the halting problem (how many "bonus points" do you get for solving *that?*). I don't want to open the "let's-hardcode-some-common-cases" can of worms. A better use of that time would be to populate the builtins library.

The best we can probably do in this case is a clever fuzzer. Feel free to volunteer to implement it on top of nearley-unparse. The fun part will be coming up with a user-friendly representation of an ambiguity's multiple parsings. I recommend a double flame diagram!

@tjvr Tim, I feel I've written basically this same comment before — it might be time to start an FAQ section that explain some of our design decisions, at least for the more common suggestions we get.

**Comment by notsonotso** [comment]
No, the grammar is not ambiguous.

**Comment by notsonotso** [comment]
I just noticed https://github.com/Hardmath123/nearley/issues/238, which is a similar issue (which seems to be closed without resolution)

**Comment by deltaidea** [comment]
@Hardmath123 You're totally right. Sorry I haven't thought this through.

@notsonotso Could you please post the nearley grammar? That would probably help with debugging.

**Comment by notsonotso** [comment]
Profiling shows Nearley spending 90% of the time in arrpush

**Comment by Hardmath123** [comment]
Yeah, okay, so same as #238, which means your best bet is to roll your own EBNF with a custom postprocessor that uses linked lists.

**Comment by notsonotso** [comment]
> your best bet is to roll your own EBNF with a custom postprocessor that uses linked lists.

I have no idea what that means. Going back antlr for now.

**Comment by notsonotso** [comment]
@tjvr Closing very real performance issues is very lame and disingenuous.

**Comment by danielspencer** [comment]
I think this was closed because it is a duplicate of an existing issue as near as we can tell. You didn't actually post the grammar to be examined/fixed so we can't really make any progress on your case specifically.

If you had posted the grammar then we could have at least checked this was the bug and demonstrated the proposed solution. You sounded like you didn't care about the issue anymore and were returning to antlr so asking you again for the grammar didn't seem productive.

This performance bug is bad but it requires a breaking change to fix as said in the existing issue. The work arounds may need to be documented more thoroughly, probably including this in the examples would help.

**Comment by notsonotso** [comment]
There's no point providing a grammar, the csv grammar in the examples is good enough to demonstrate the problem on large input.
