### ISSUE TITLE
Support HTTPS on nearley.js.org website

### ISSUE THREAD

**Issue by deltaidea** [Hardmath123/nearley#255]
Not that there's any sensitive data, but still a good idea to keep it secure.

Someone needs to submit a PR to https://github.com/js-org/dns.js.org and remove `//noCF?` after the domain name there.

Taken [from here](https://github.com/js-org/dns.js.org/blob/master/cnames_active.js#L17-L21):

```
JS.ORG uses CloudFlare as its DNS. By default, CloudFlare proxies all requests to your subdomain
to get SSL support (https://foo.js.org) and make use of browser caching with a TTL of 30 min.
But you can opt-out from this and make Cloudflare forward all requests directly to GitHub.
Just add '//noCF' in the line of your requested subdomain to give me a hint.
(all the lines marked with '//noCF?' are from a time when a requester had to explicitly opt-in;
```

**Comment by Hardmath123** [comment]
This would be nice (I'm not a fan of the 30min cache, but SSL is probably worth it). Not quite sure I understand what to do here, since https://github.com/js-org/dns.js.org/blob/master/cnames_active.js#L538 says "(don't add this in a new PR)". If you understand the process, feel free to do the necessary steps.

**Comment by deltaidea** [comment]
Done!
