### ISSUE TITLE
When to use moo and when to use builtins

### ISSUE THREAD

**Issue by notsonotso** [Hardmath123/nearley#277]
I'm confused about when to use a lexer like moo and when to use Nearley rules.

    number: /[0-9]+/,

in moo, versus

    @builtin "number.ne"

or even your own custom Nearley rules.

Could someone provide some guidelines? Are there performance implications in choosing one over the other?

**Comment by tjvr** [comment]
> Are there performance implications in choosing one over the other?

Yes! As we wrote [in the docs](https://nearley.js.org/docs/tokenizers), lexers often make your parser faster by an order of magnitude.

The reason is that nearley is very clever; but lexing is a pretty easy job, and can be done much faster by a lexer, which is quite stupid.

For the same reason, this tends to makes your grammar easier to write, since the lexer's done the tedious bit for you. Most languages are parsed this way: for example, Python has a tokenizer which splits the input into tokens, interspersed with special INDENT and DEDENT tokens.

If you like, you can do clever things like ignoring whitespace, to make the grammar even simpler! (Although currently ignoring whitespace in a nearley lexer isn't as easy as we'd like; you have to implement the [lexer interface](https://nearley.js.org/docs/tokenizers#custom-lexers) yourself).

We absolutely recommend using a lexer if possible, and we should definitely make this clearer in the docs. Perhaps we should de-emphasize those builtins @Hardmath123?

**Comment by notsonotso** [comment]
@tjvr Sounds like good advice. Thanks!

**Comment by Hardmath123** [comment]
Yes — adding onto what @tjvr said, the builtins are there to help you prototype a grammar really quickly. They are efficient in the sense that you can type them quickly, but inefficient in the sense that they make your parser slower! Thus, for any "real" project, you would want to switch to a lexer and take the extra time to implement these primitives yourself.
