### ISSUE TITLE
Understanding the parse result

### ISSUE THREAD

**Issue by notsonotso** [Hardmath123/nearley#279]
As a test, I have a super-simple grammar that accepts numbers across lines.

However, the result has an incredible amount of array-nesting, which increases if the input has multiple lines.

For instance, the input "4" yields

```
[[[[{"type":"number","value":"4","text":"4","offset":0,"lineBreaks":0,"line":1,"col":1}]]],null]
```

Why four levels of arrays? And more if there are more lines.

In general, what are the rules for traversing the result as an AST? It's hard to know how deep you need to start looking for actual objects. What does the arrays signify at each level?

Grammar below (yes, over-complicated for numbers, but this is the starting point for something else):

```
@{%
const moo = require("moo");

const lexer = moo.compile({
    ws: {match: /[ \t\n\r]+/,  lineBreaks: true },
    number: /[0-9]+/,
});
%}

@lexer lexer

start -> exprlist:* %ws:?
exprlist -> expr
    | exprlist %ws expr
expr -> %number
```

**Comment by tjvr** [comment]
@Hardmath123 will be along later to explain better, but I recommend [reading about postprocessors](https://nearley.js.org/docs/grammar#postprocessors): 🙂

> By default, nearley wraps everything matched by a rule into an array.

**Comment by Hardmath123** [comment]
Right. The first level of array-ness (which has `null` as element 2) matches the `start` nonterminal. The first element matches the `exprlist:*`. The second element, `null`, represents the fact that the `%ws:?` item was not matched — "4" has no whitespace after it.

The second level of array-ness comes from the `exprlist:*` item. `:*` as you know means "match zero or more of these". That means the "result" is actually an array of results, where each element in the array represents one `exprlist`. Since the input "4" only matches one `exprlist`, that array has one element.

The third level of array-ness is from the fact that you matched one `expr` in an `exprlist`, from the rule `exprlist -> expr`. Why is this in an array? Well, even though there's only one item in the rule (`expr`), nearley always returns an array as the result: one element for each item. So, the first element in that array represents a parsed `expr`. If the rule was `exprlist -> expr "cow"` then the array would have two elements: one for the `expr` and one for the string `"cow"`.

You can probably guess the fourth level of array-ness already, now! It's from the rule `expr -> %number`, which returns a single-element array for exactly the same reason that the rule `exprlist -> expr` does.

Okay, so, how do we fix this? The easy answer is to use postprocessors (see Tim's link). For example,

```
expr -> %number {% function(d) {return d[0];} %}
```

will now make `expr` return the contents of the `%number`, _not_ an array! (It extracts the first element of the result array by doing `d[0]`).

In fact, the function `function(d) {return d[0]; } %} is so common, nearley provides it automatically: you can simply write

```
expr -> %number {% id %}
```

**Comment by notsonotso** [comment]
> By default, nearley wraps everything matched by a rule into an array.

Oh my, not something I want.

Ideally, I'd like for Nearley to provide parser callbacks like Antlr does. That is, when "number" is matched, I would get a call to "on_number" on my parser listener.

**Comment by Hardmath123** [comment]
Well, you can think of it as nearley providing rule-level callbacks.

**Comment by Hardmath123** [comment]
Looks like I've answered the top-level question, though, so I'm going to close this. Let us know if you have other questions on this topic.

**Comment by notsonotso** [comment]
@Hardmath123 I think you close issues a bit too fast. I have a follow-up question.

> Well, you can think of it as nearley providing rule-level callbacks

What does this mean? How do I register these callbacks?

**Comment by Hardmath123** [comment]
In the rule `a -> b c d {% function(d) {…} %)`, the function acts as a rule-level "callback". We call it a postprocessor.

The top-level question was "what do these nested arrays signify?", and I think I've answered that well enough to close this issue.

**Comment by notsonotso** [comment]
@Hardmath123 ok, I'd rather work with an AST (with a callback interface) than spread logic all over the grammar. I'd like a clean grammar.
