### ISSUE TITLE
Macro examples in documentation do not compile

### ISSUE THREAD

**Issue by fauxneticien** [Hardmath123/nearley#290]
I wish I could be more helpful than reporting that the macro examples in the documentation do not compile (neither in the nearley playground nor with `nearleyc` 2.11.0 in the Terminal), but I'm only just trying to learn about macros in nearley.

For some reason the compiler is saying `Error: Unknown macro: ____`, even though it is clearly defined in the grammar.

#### In the playground

![screen shot 2017-09-04 at 4 46 06 pm](https://user-images.githubusercontent.com/9938298/30014831-a9a37608-9191-11e7-8ced-bd468f071093.png)
![screen shot 2017-09-04 at 4 46 51 pm](https://user-images.githubusercontent.com/9938298/30014861-bbdf8c80-9191-11e7-9738-2796d22c2404.png)

#### With `nearleyc` 2.11.0

[![asciicast](https://asciinema.org/a/rB8D25j3nteSbuQFIkvbU8fHj.png)](https://asciinema.org/a/rB8D25j3nteSbuQFIkvbU8fHj)

**Comment by Hardmath123** [comment]
Hey @fauxneticien — thanks for the report! At some point, I must have absentmindedly rewritten those examples and forgotten to check if they still compile.

The issue is that macros must be defined before usage. This lets you shadow them if needed, and enforces some sanity when you have multiple `@import`ed grammars (I learned this the hard way!). So, moving the `main ->` lines in the examples to the bottom of the file lets them compile just fine.

```
$ cat - | pbcopy
# Matches "'Hello?' 'Hello?' 'Hello?'"
matchThree[X] -> $X " " $X " " $X
inQuotes[X] -> "'" $X "'"

main -> matchThree[inQuotes["Hello?"]]

$ nearley-test -q -i "'Hello?' 'Hello?' 'Hello?'" <(nearleyc <(pbpaste))
[ [ [ [ [ '\'', [ 'Hello?' ], '\'' ] ],
      ' ',
      [ [ '\'', [ 'Hello?' ], '\'' ] ],
      ' ',
      [ [ '\'', [ 'Hello?' ], '\'' ] ] ] ] ]
```

I fixed this in the docs via d29b5a1. Sorry about that. Maybe we need tests for our docs, now! Meanwhile, please let me know if you have any other issues.

P.S. I just realized how clever your username was. :-)
