### ISSUE TITLE
Nearley produces 14 identical results

### ISSUE THREAD

**Issue by are1000** [Hardmath123/nearley#325]
I'm pretty sure its due to an ambigious grammar, but I don't even know how to start fixing it - because all generated ASTs are identical. What to do in such situation?

**Comment by tjvr** [comment]
It can be very difficult! You might like to try:

- Removing/disabling your postprocessors
- Looking at your whitespace rules very carefully; whitespace is often a problem
- Switching to a [tokenizer](https://nearley.js.org/docs/tokenizers): this often removes potential for ambiguity, just because your rules become simpler :-)

**Comment by are1000** [comment]
Thanks for your help! In this case, it was indeed connected to whitespace - somehow two `_` `_` ended next to each other.

**Comment by tjvr** [comment]
Glad to hear it :-)
