### ISSUE TITLE
Named tokens

### ISSUE THREAD

**Issue by Hardmath123** [Hardmath123/nearley#58]
Provide a way to name a token, and bind these names by augmenting the data array to an object.

```
a -> name:string {% function(d) {return d.name;} %}
```

**Comment by matthew-dean** [comment]
So... Okay, so I think I was reading this backwards before (and hence my backwards examples). You're saying ```string``` is the token name (and not a type), and name is the object label assigned to the token?

In other words:
```
a -> space:_ {% function(d) {return d.space;} %}
# returns " "
```
?

Okay, I think I'm getting it now. So, in a more complex (but not ideal grammar) example:
```
a -> id:[\w]:+ _ count:[0-9]:*

# "cow 999" returns { id: ['c','o','w'], count: ['9','9','9'] }
```
Correct?

**Comment by Hardmath123** [comment]
Yes, precisely, that's how I meant it originally. However, rather than returning the object `{ id: ['c','o','w'], count: ['9','9','9'] }`, it would actually return the array with the relevant properties set (because you can do gunk like that in JavaScript).

```js
result.constructor => Array
result.id => 'cow'
result.count => 999
result => ['cow', 999]
```

By the way, I think that's a pretty general issue with using colons—it's not immediately obvious whether the left side is the label or the nonterminal name. What did you think of the dot syntax?

```
a -> astringnonterminal.name _ anintegernonterminal.count {% function(d) {return [d.name, d.count]; } %}
```

**Comment by matthew-dean** [comment]
Hmm, it's still kind of weird-looking to me, because there are so many template languages that use that to explicitly refer to the property of an object. So, I still had to think about what was the label and what was the nonterminal, even though it was explicit. That's why I think separating them entirely from grammar is smarter, because it's actually more explicit, and it keeps the grammar itself more readable. This, to me, is really easy to follow.

```
a -> astringnonterminal _ anintegernonterminal  {name, null, count}  {% function(d) {return [d.name, d.count]; } %}
```
I can read the grammar as grammar, the object / array assignment as one piece, and the processing function as the next. They're not semantically confused with each other. Right now, the grammar is JUST about parsing rules. Sticking labeling inline, I don't know. It just seems like it mucks it up and makes the grammar itself more confusing, and still leaves the key assignment still somewhat confusing, so I don't think putting it inline is a win.

I think you could also use the assignment form to further clean up long grammar in a more "documentation" style.
```
a -> astringnonterminal      {name}
     _                       {}
     anintegernonterminal    {count}       {% function(d) {return [d.name, d.count]; } %}
```
For me, when I'm looking at that, I can just visually take in the parsing grammar, or take in labeling, or just look at each nonterminal with it's label. So I don't have to "skip" over noise that I'm not trying to read at the moment.

That's just my $0.02.

**Comment by matthew-dean** [comment]
And, technically, the second example above is "inline", but it's a syntax that lends itself more to arbitrary whitespace separation over the colon or dot syntax. So maybe that's the thing for me, being able to separate labeling from parsing rules in some form.

**Comment by matthew-dean** [comment]
But that said, I know you said you could just write custom functions to not have inline labeling - https://github.com/Hardmath123/nearley/issues/55#issuecomment-100063486. And if that's the preferred way to do it, then why add inline labeling?

**Comment by matthew-dean** [comment]
Of course, I'm also biased to using braces this way, since that's close to Less's interpolation syntax. ;-)

**Comment by Hardmath123** [comment]
Ah, I see.

Once of the reasons I support "inline" naming is because it makes it really
easy to splice in a token without having to fix a lot of indices in the
postprocessor. For example, if I have `a -> b c` and I later decided I
wanted whitespace between `b` and `c`, I'd have to change all the `d[1]`s
to `d[2]`s in the postprocessor. If `b` and `c` were named inline, I
wouldn't have to do so. I feel it doesn't really make sense to have naming
if it's not inline.

I actually like `a -> astring {name} anumber {value}` (your last example)
very much---it seems much cleaner than dots. I read that as "`a` expands to
`astring` (which is the name) followed by `anumber` (which is the value)".

Ideally, this type of inline documentation would be the norm, and we would
never have to bother with the `d` array at all. But backward-compatibility
is a thing, so that would have to be a goal for 2.0.0+.

**Comment by matthew-dean** [comment]
> Once of the reasons I support "inline" naming is because it makes it really
easy to splice in a token without having to fix a lot of indices in the
postprocessor. 

Yeah, it would be nice to minimize the amount of times someone needs to write a postprocessing function just to drop out a token or do simple naming.

> I actually like `a -> astring {name} anumber {value}` (your last example)
very much---it seems much cleaner than dots. I read that as "`a` expands to
`astring` (which is the name) followed by `anumber` (which is the value)".

I think we're on the same page, if by the name and value you meant a property named "name" and "value" on the resulting data object.

To me, this would be another way to drop a token from output. (Incidentally, am I using the word "token" correctly? You've called them nonterminals. I don't know my grammar grammar.) That is, I think it can be safe to imply that if someone labels some items and not others, then the others can be dropped because they'd have no assigned property.

**Comment by Hardmath123** [comment]
> I think we're on the same page, if by the name and value you meant a property named "name" and "value" on the resulting data object.

Yep.

> Incidentally, am I using the word "token" correctly? You've called them nonterminals. I don't know my grammar grammar.

Eh, it's a nebulous definition. A "nonterminal" is anything that has one or more rules defined for its expansion (`a` is a nonterminal in `a -> "cow" a {% … %}`). A "terminal" is basically a character or charclass. I use "token" to mean the set union of "nonterminal" and "terminal". So, each "token" has a member in the "d" array.

Formally, a "token" would be an item that a lexer yields (lexers yield a *stream* of tokens). So, for example, a JSON lexer would return tokens like "open left curly brace" or "number" or "string" or "colon" or "comma", etc. Nearley doesn't have a lexer (neither does less.js's parser), so this doesn't apply*.

*Ok, technically nearley is capable of working with lexer output. You can feed it an array of anything instead of a string, and it would work. You just can't use the grammar compiler; you'll have to write the grammar in JavaScript (which isn't terrible—the grammar for `.ne` files was written in JS before the amazing @rwindelz bootstrapped it for me).

**Comment by bojidar-bg** [comment]
:+1: (Though +1's never fix things on themselves...)

**Comment by tjvr** [comment]
A breaking change, but I think a nicer solution to this would be to use apply() instead of call() for preprocessors. So you get arguments, rather than a single array argument.

Then you can write:

    a -> [\w]:+ _ [0-9]:*   {% (id, _, count) %}

**Comment by Hardmath123** [comment]
That's… actually really clever. Now I regret using .call(). But there's no way we can do this — it'll break too many (i.e. every single one of the) existing grammars. Maybe for v3.0, if we ever get there.

**Comment by tjvr** [comment]
> there's no way we can do this

Right, not for `nearleyc`. But for when you support tagged ES6 literals... ;-)

```js
let myDslGrammar = bnf`

file --> NL file                  ${(a, b) => b}
      | file NL                   ${(a, b) => a}
      | file blankLines script    ${(a, b, c) => a.concat([c])}
      | script                    ${a => [a]}

blankLines --> NL NL
            | blankLines NL

script => cheese                  ${a => a}

cheese => 'hello' foo 'world'     ${function() { return ['hello:world', arguments[3]] }}
       | '1'

foo --> thing                     ${a => a}
      | thing2                    ${a => a}
      | op                        ${a => a}

thing => 'sweet'                  ${() => ['sweetConstant']}
       | 'happy'                  ${() => ['happyConstant']}

thing2 => 'swe'                   ${() => ['shortConst']}

op => 'really' foo                ${(a, b) => ['really', b]}

op => foo 'and' foo               ${(a, b, c) => ['+', a, c]}

int --> /[0-9]+/                  ${parseInt}

NL --> '\n'
SEP --> ' '
      | NL
`
```

**Comment by arcanis** [comment]
> A breaking change, but I think a nicer solution to this would be to use apply() instead of call() for preprocessors. So you get arguments, rather than a single array argument.
> 
> Then you can write (in ES6 at least):
> 
> ```
> a -> [\w]:+ _ [0-9]:*   {% (id, _, count) => ({ id, count }) %}
> ```

That's still kinda possible by destructuring the parameter:

```
a -> [\w]:+ _ [0-9]:*   {% ([ id, _, count ]) => ({ id, count }) %}
```

**Comment by tjvr** [comment]
@arcanis Ah, good point. Nice.

**Comment by tjvr** [comment]
Given the proposed ES6 solution, I
