### ISSUE TITLE
Calling nearley-test on a specific grammar results in 100% cpu usage and running for an indefinite amount of time

### ISSUE THREAD

**Issue by Naissur** [Hardmath123/nearley#82]
If `nearley-test grammar.js -i <some input>` is called with grammar.js ([pastebin](http://pastebin.com/uWcJPxGV)) containing a compiled grammar of

```
main -> a

a -> .:* a .:*  
   | null
```

The node process consumes 100% of the cpu and does not seem to stop in a reasonable amount of time. Oddly enough, removing `| null` makes it work.

**Comment by Hardmath123** [comment]
This is actually expected behavior! You've found a very interesting corner-case where there are an *infinite* number of possible parsings of the empty string:

`""` = `null` = `.:* (null) .:*` = `.:* (.:* (null) .:*) .:*` = …

where each `.:*` matches zero `.`'s. Nearley tries to give you all of these parsings, so it goes into an infinite loop.

Depending on what you're trying to do, there are different ways to fix this grammar so that it isn't ambiguous. Let me know if you need any help.

**Comment by Naissur** [comment]
Oh, that's cool! Thank you for explaining :)

The original reason for this behavior was a typo - `a -> .:* a .:*` should have been `b -> .:* a .:*`, so it's no longer infinitely ambiguous :). 

Thanks for a cool project!
