### ISSUE TITLE
why can't I re-use the same parser object?

### ISSUE THREAD

**Issue by seiyria** [Hardmath123/nearley#98]
[Here is my nearley scripts](https://github.com/seiyria/deck.zone/blob/master/decklang/decklang.ne) and [here is my test script](https://github.com/seiyria/deck.zone/blob/master/decklang/test/testdeck.js).

Suppose I move the `parser` declaration outside of the forEach, then if I run two `feed()` calls the second one will be at offset 31. This leads me to two questions:

* why is it at offset 31? Is it just chaining all of the inputs together when using feed?
* is it advisable to _not_ reuse the same parser object? my scripts could potentially be ~10k lines at most so I don't know if there's a huge performance hit from instantiating a parser 10k times.

**Comment by Hardmath123** [comment]
Ah, this has come up before. The thing is, you can't think of a parser as a reusable object here, because a parser object maintains some "state" inside it. It's like how you can't really reuse a teabag because the process of using a teabag _changes_ the teabag.

The reason `feed()` chains input is because nearley is a _streaming_ parser: you can incrementally give it parts of a string and it'll parse it as it gets it. The use-case here is if you're reading a really long string from a file or from the network. One way to parse a long string is to first get all of it from the network, then parse it. But it's much nicer if you can start parsing the string as chunks of it get downloaded over a slow connection—and you get the benefit of not having to store the entire string in memory at once.

Are you using a separate parser for each line of code in your scripting language? I think you should, ideally, be using a single parser for an entire script, and write the parser so that it understands a multiline file. That's how all "real-world" languages are parsed. This lets you, for example, have a line break in the middle of a long statement without repurcussions:

```
console.log(
 thisIsAVeryLongStatementThatWillNotFitOnASingleLine();
);
```

Hope this helps!

**Comment by seiyria** [comment]
Ideally, yeah, I would like to use a single parser for the entire script. I guess then it's just a matter of figuring out how to do that. I'm guessing I'll need to adjust my `main` node?

Also, since I'd be using a single parser... eventually, I wanted to implement variables. Variables would just be string substitution for me, so:

```
[TitleFont]=Arial, 16, BB, #000000
font=[TitleFont]
```

and 
```
[TitleFont]=Arial
[TitleFontSize]=16
font=[TitleFont], [TitleFontSize], BB, #000000
```

would be equivalent (it's essentially just like a macro in C - copy/pasted all over the place). I was going to try to make it parse one statement at a time, and then do a bit of preprocessing on a string if I have any variables that are in the next statement, then apply them. I'm sure something like that is possible, but is there any docs on doing something like that?

Thanks! I'll close this issue regardless since I did get an answer.

**Comment by Hardmath123** [comment]
Yeah, you can do something like:

`main -> whitespace (line_of_code whitespace):*`

to parse all the lines of a file.

I would do the replacement on the parsed structure, not the input string. Do something like:

```
macrodefinition -> "[" name "]" "=" value
value -> number | fontname | hexcolor | … | macrovalue
```

Then, once you have parsed the string, you can traverse the parsing output to find "macrodefinition"s and keep a dictionary of them. Then traverse again, searching for "macrovalue"s and replace them with the corresponding "macrodefinition" entry.

Nearley itself has a "macro" feature which you can read about in the readme; it works the way I described above.

```
withX[str] -> "XXX" $str

main -> withX["cow"] # this matches "XXXcow"
```

**Comment by seiyria** [comment]
Cool. Thanks for all the help again, I'm pretty new to ... well, all of this. I wasn't sure if nearleys macros worked like I was expecting, but it sounds like it's something to look into. Looks like I'm going to have to restructure a lot of things to make it work, but better now than later.
